spring:
  cache:
    type: redis
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    #JPA Primary Setting
    driver-class-name: 'org.h2.Driver'
    jdbc-url: 'jdbc:h2:mem:test'
    username: test
    password: 1234
  datasources:
    nosql:
      redis:
        redis00:
          host: localhost
          port: 6379
          password: 1234
        redis01:
          host: localhost
          port: 6379
          password: 1234
  data:
    redis:
      lettuce:
        pool:
          max-active: 5
          max-idle: 5
          min-idle: 2
      host: localhost
      port: 6379
      password: 1234

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    level:
  logback:
    rollingpolicy:
      max-history: 15
      file-name-pattern: "/test/program/logs/service.log.%d{yyyy-MM-dd}.%i"
  level:
    root: info
server:
  port: 8079
  servlet:
    context-path: "/api/v1"
